# Swing Vision Transformation

#### Converting SwingVision data into our format

#### Trying to find other swingvision data:

- https://bubbletao.com/2019/03/31/tennis-score-tracking-and-exported-data-analysis-with-apple-watch-using-swing-app/  (no data, but walks through common errors and fixes in data)

# Comparing website manually tagged data

### Load in Data

In [1]:
import pandas as pd
import numpy as np
import os 
import re

# Option to display max rows/columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
clean_df = pd.read_csv('Cleaned [WEBSITE] Elise_Wagle_Texas_Tech_Full_Match - Cleaned [WEBSITE] Elise_Wagle_Texas_Tech_Full_Match.csv')

In [3]:
clean_df.shape

(694, 57)

In [4]:
clean_df.head(20)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
0,0-0,0-0,0-0,1.0,6749,NaN,NaN,NaN,NaN,1,Deuce,Player2,Near,1.0,Body,-72.0,181.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UCLA,5/4/14,D1,NCAA,4.0,NaN,Los Angeles Tennis Center,Texas Tech,Elise Wagle,Motka Komac,right,right,2.0,Hard,NaN
1,0-0,0-0,0-0,NaN,10039,NaN,NaN,NaN,NaN,2,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-155.0,472.0,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-23.0,-441.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-0,0-0,0-0,NaN,11629,NaN,NaN,NaN,NaN,3,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,-547.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,445.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,13157,NaN,NaN,NaN,NaN,4,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,507.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37.0,-262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-0,0-0,0-0,NaN,14863,NaN,NaN,NaN,NaN,5,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-107.0,-544.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,210.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0-0,0-0,0-0,NaN,16233,NaN,NaN,NaN,NaN,6,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0,480.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.0,-195.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0-0,0-0,0-0,NaN,18230,NaN,NaN,NaN,NaN,7,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0,-531.0,Crosscourt,Forehand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-39.0,405.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0-0,0-0,0-0,NaN,19945,NaN,NaN,NaN,NaN,8,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-35.0,390.0,Crosscourt,Forehand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,-265.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0-0,0-0,0-0,NaN,21123,NaN,NaN,NaN,NaN,9,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.0,-414.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,224.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0-0,0-0,0-0,NaN,22522,NaN,NaN,NaN,NaN,10,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,478.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21.0,-201.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0-0,0-0,0-0,NaN,23537,1.0,NaN,NaN,NaN,11,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-19.0,-211.0,Down the Line,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,-61.0,269.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,15-0,0-0,0-0,1.0,52273,NaN,NaN,NaN,NaN,1,Ad,Player2,Near,1.0,Body,91.0,235.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,15-0,0-0,0-0,NaN,55152,NaN,NaN,NaN,NaN,2,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,473.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-58.0,-264.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,15-0,0-0,0-0,NaN,57002,NaN,NaN,NaN,NaN,3,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-99.0,-477.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-122.0,430.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15-0,0-0,0-0,NaN,57892,NaN,NaN,NaN,NaN,4,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-93.0,502.0,Down the Line,Forehand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-58.0,-339.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15-0,0-0,0-0,NaN,60066,1.0,66672.0,NaN,NaN,5,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.0,-429.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,-11.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,15-15,0-0,0-0,1.0,61434,NaN,NaN,NaN,NaN,1,Deuce,Player2,Near,0.0,Body,-56.0,2.0,1.0,Wide,-117.0,235.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,15-15,0-0,0-0,NaN,96639,NaN,NaN,NaN,NaN,2,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-205.0,480.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,-350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,15-15,0-0,0-0,NaN,98098,NaN,NaN,NaN,NaN,3,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123.0,-510.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-90.0,285.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,15-15,0-0,0-0,NaN,99954,NaN,NaN,NaN,NaN,4,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-128.0,472.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,-363.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Notebook Start

### Load in data

In [1]:
import pandas as pd
import numpy as np
import os 
import re

# Option to display max rows/columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
# Input file name here
your_file_name = 'aadarsh_allamerican.xlsx'
swing_data = pd.read_excel(your_file_name, sheet_name='Shots')
swing_data.shape

(982, 25)

In [3]:
swing_data.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Luca Staeheli,1,first_serve,Serve,Slice,118.400520,1,1,1,short,ad,far,0.378870,16.762121,out,deuce,near,1.135853,-0.554549,2.673766,down the T,Out,False,21:27:07,17.920000
1,Aadarsh Tiprathi,1,none,Backhand,Slice,53.254807,1,1,1,deep,deuce,far,-0.750807,20.385843,out,deuce,far,-0.694103,26.614202,1.223969,inside out,Net,False,21:27:08,18.969999
2,Luca Staeheli,1,second_serve,Serve,Slice,76.265121,1,1,1,short,deuce,far,-0.731950,16.227081,deep,deuce,near,0.803059,-0.379706,2.749103,down the T,In,False,21:27:17,27.410000
3,Aadarsh Tiprathi,2,second_return,Backhand,Topspin,54.827156,1,1,1,short,ad,near,-0.973862,7.295816,deep,deuce,far,-1.363457,24.678232,1.643152,inside in,In,False,21:27:18,28.320000
4,Luca Staeheli,3,serve_plus_one,Backhand,Topspin,60.095497,1,1,1,deep,ad,far,2.046510,20.453445,deep,ad,near,-0.583427,0.621297,0.803284,cross court,In,False,21:27:19,29.570000

### Clean swing vision data

In [4]:
swing_data.query('Stroke == "Feed"').head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
12,Aadarsh Tiprathi,0,none,Feed,Slice,19.918634,2,1,1,short,ad,near,-0.430203,5.804375,deep,deuce,far,-0.957253,21.578362,2.052984,---,In,False,21:27:38,48.709999
24,Aadarsh Tiprathi,0,none,Feed,Flat,23.382744,5,1,1,deep,ad,near,-0.044347,3.948372,deep,deuce,far,-3.760015,21.839136,0.972103,---,In,False,21:29:00,130.149994
35,Luca Staeheli,0,none,Feed,Flat,24.871349,7,2,1,short,deuce,far,-1.670223,13.518161,out,deuce,far,-2.310343,25.097612,1.392078,---,Net,False,21:30:59,249.460007
50,Luca Staeheli,0,none,Feed,Flat,19.052607,9,2,1,deep,deuce,near,0.584094,4.607936,short,ad,far,2.249055,18.122910,3.073324,---,In,False,21:32:19,329.100006
81,Luca Staeheli,0,none,Feed,Flat,24.438272,12,2,1,short,ad,far,0.324774,15.704046,deep,deuce,far,-0.530713,23.145393,1.785928,---,Net,False,21:34:35,465.709991

In [5]:
swing_data.query('Shot == 0').head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
12,Aadarsh Tiprathi,0,none,Feed,Slice,19.918634,2,1,1,short,ad,near,-0.430203,5.804375,deep,deuce,far,-0.957253,21.578362,2.052984,---,In,False,21:27:38,48.709999
24,Aadarsh Tiprathi,0,none,Feed,Flat,23.382744,5,1,1,deep,ad,near,-0.044347,3.948372,deep,deuce,far,-3.760015,21.839136,0.972103,---,In,False,21:29:00,130.149994
35,Luca Staeheli,0,none,Feed,Flat,24.871349,7,2,1,short,deuce,far,-1.670223,13.518161,out,deuce,far,-2.310343,25.097612,1.392078,---,Net,False,21:30:59,249.460007
50,Luca Staeheli,0,none,Feed,Flat,19.052607,9,2,1,deep,deuce,near,0.584094,4.607936,short,ad,far,2.249055,18.122910,3.073324,---,In,False,21:32:19,329.100006
81,Luca Staeheli,0,none,Feed,Flat,24.438272,12,2,1,short,ad,far,0.324774,15.704046,deep,deuce,far,-0.530713,23.145393,1.785928,---,Net,False,21:34:35,465.709991

In [6]:
swing_data.query('Type == "none"').head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
1,Aadarsh Tiprathi,1,none,Backhand,Slice,53.254807,1,1,1,deep,deuce,far,-0.750807,20.385843,out,deuce,far,-0.694103,26.614202,1.223969,inside out,Net,False,21:27:08,18.969999
12,Aadarsh Tiprathi,0,none,Feed,Slice,19.918634,2,1,1,short,ad,near,-0.430203,5.804375,deep,deuce,far,-0.957253,21.578362,2.052984,---,In,False,21:27:38,48.709999
24,Aadarsh Tiprathi,0,none,Feed,Flat,23.382744,5,1,1,deep,ad,near,-0.044347,3.948372,deep,deuce,far,-3.760015,21.839136,0.972103,---,In,False,21:29:00,130.149994
35,Luca Staeheli,0,none,Feed,Flat,24.871349,7,2,1,short,deuce,far,-1.670223,13.518161,out,deuce,far,-2.310343,25.097612,1.392078,---,Net,False,21:30:59,249.460007
50,Luca Staeheli,0,none,Feed,Flat,19.052607,9,2,1,deep,deuce,near,0.584094,4.607936,short,ad,far,2.249055,18.122910,3.073324,---,In,False,21:32:19,329.100006

#### Remove all the rows where it is a feed

In [7]:
rows_to_drop = swing_data.query('Type == "none"').index
swing_data = swing_data.drop(rows_to_drop)
# Important to reindex to avoid missing indicies
swing_data = swing_data.reset_index(drop=True)
swing_data.shape

(847, 25)

In [8]:
swing_data.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Luca Staeheli,1,first_serve,Serve,Slice,118.400520,1,1,1,short,ad,far,0.378870,16.762121,out,deuce,near,1.135853,-0.554549,2.673766,down the T,Out,False,21:27:07,17.92
1,Luca Staeheli,1,second_serve,Serve,Slice,76.265121,1,1,1,short,deuce,far,-0.731950,16.227081,deep,deuce,near,0.803059,-0.379706,2.749103,down the T,In,False,21:27:17,27.41
2,Aadarsh Tiprathi,2,second_return,Backhand,Topspin,54.827156,1,1,1,short,ad,near,-0.973862,7.295816,deep,deuce,far,-1.363457,24.678232,1.643152,inside in,In,False,21:27:18,28.32
3,Luca Staeheli,3,serve_plus_one,Backhand,Topspin,60.095497,1,1,1,deep,ad,far,2.046510,20.453445,deep,ad,near,-0.583427,0.621297,0.803284,cross court,In,False,21:27:19,29.57
4,Aadarsh Tiprathi,4,return_plus_one,Backhand,Topspin,57.061077,1,1,1,deep,deuce,near,0.761086,1.642498,out,ad,far,2.400083,25.378126,1.205338,down the line,In,False,21:27:20,30.76

### Load in Points data

In [9]:
your_file_name = 'EliseWagle_TexasTech_OriginalScore.xlsx'
swing_data_points = pd.read_excel(your_file_name, sheet_name='Points')
swing_data_points.shape

(132, 15)

In [10]:
def create_point(server, player1score, player2score):
    if server == "host":
        return str(player1score) + "-" + str(player2score)
    else:
        return str(player2score) + "-" + str(player1score)
    
swing_data_points['pointScore'] = swing_data_points.apply(lambda x: create_point(x['Match Server'], x['Host Game Score'], x['Guest Game Score']), axis=1)

In [11]:
swing_data_points = swing_data_points.rename(columns={'Break Point' : 'isBreakPoint'})
swing_data_points['isBreakPoint'] = swing_data_points['isBreakPoint'].replace(False, '')
swing_data_points['isBreakPoint'] = swing_data_points['isBreakPoint'].replace(True, 1)

In [12]:
swing_data_points = swing_data_points[['Point', 'pointScore', 'isBreakPoint']]
swing_data_points

     Point pointScore isBreakPoint
0        1        0-0
1        2       15-0
2        3      15-15
3        4      30-15
4        5      30-30
5        6      30-40            1
6        7      40-40            1
7        8        0-0
8        9       15-0
9       10       30-0
10      11       40-0
11      12        0-0
12      13       0-15
13      14      15-15
14      15      15-30
15      16      30-30
16      17      40-30
17      18        0-0
18      19       15-0
19      20       30-0
20      21       40-0
21      22        0-0
22      23       15-0
23      24      15-15
24      25      30-15
25      26      30-30
26      27      30-40            1
27      28        0-0
28      29       0-15
29      30       0-30
30      31      15-30
31      32      30-30
32      33      30-40            1
33      34        0-0
34      35       0-15
35      36      15-15
36      37      30-15
37      38      40-15
38      39        0-0
39      40       15-0
40      41       30-0
41      42      30-15
42      43      30-30
43      44      40-30
44      45        0-0
45      46       15-0
46      47      15-15
47      48      15-30
48      49      15-40            1
49      50      30-40            1
50      51      40-40            1
51      52        0-0
52      53       0-15
53      54      15-15
54      55      15-30
55      56      15-40            1
56      57        0-0
57      58       15-0
58      59       30-0
59      60      30-15
60      61      40-15
61      62        0-0
62      63       15-0
63      64       30-0
64      65       40-0
65      66        0-0
66      67       15-0
67      68       30-0
68      69       0-40
69      70      15-40
70      71      AD-15
71      72       0-15
72      73       15-0
73      74        0-0
74      75       15-0
75      76      15-15
76      77      15-30
77      78      15-40            1
78      79      30-40            1
79      80      40-40            1
80      81        0-0
81      82       0-15
82      83      15-15
83      84      15-30
84      85      15-40            1
85      86      30-40            1
86      87      40-40            1
87      88        0-0
88      89       0-15
89      90      15-15
90      91      15-30
91      92      30-30
92      93      30-40            1
93      94      40-40            1
94      95        0-0
95      96       0-15
96      97      15-15
97      98      30-15
98      99      30-30
99     100      30-40            1
100    101        0-0
101    102       15-0
102    103       30-0
103    104      30-15
104    105      40-15
105    106      40-30
106    107      40-40            1
107    108        0-0
108    109       15-0
109    110       30-0
110    111      30-15
111    112      40-15
112    113      40-30
113    114        0-0
114    115       15-0
115    116      15-15
116    117      15-30
117    118      15-40            1
118    119      30-40            1
119    120      40-40            1
120    121        0-0
121    122       15-0
122    123      15-15
123    124      30-15
124    125      30-30
125    126      40-30
126    127        0-0
127    128       15-0
128    129       30-0
129    130      30-15
130    131      30-30
131    132      40-30

In [13]:
swing_data = pd.merge(swing_data, swing_data_points, on='Point')

### Load in Games data

In [14]:
your_file_name = 'EliseWagle_TexasTech_OriginalScore.xlsx'
swing_data_games = pd.read_excel(your_file_name, sheet_name='Games')
swing_data_games.shape

(22, 9)

In [15]:
swing_data_games.head()

,Game,Set,Server,Host Set Score,Guest Set Score,Game Winner,Start Time,Video Time,Duration
0,1,1,guest,0,0,host,02:39:46,NaN,214.369995
1,2,1,host,1,0,host,02:43:21,NaN,221.029999
2,3,1,guest,2,0,guest,02:47:02,NaN,202.399994
3,4,1,host,2,1,host,02:50:24,NaN,181.970001
4,5,1,guest,3,1,host,02:53:26,NaN,210.300003

In [16]:
def create_game(player1game, player2game):
        return str(player1game) + "-" + str(player2game)
    
swing_data_games['gameScore'] = swing_data_games.apply(lambda x: create_game(x['Host Set Score'], x['Guest Set Score']), axis=1)

In [17]:
swing_data_games.head()

,Game,Set,Server,Host Set Score,Guest Set Score,Game Winner,Start Time,Video Time,Duration,gameScore
0,1,1,guest,0,0,host,02:39:46,NaN,214.369995,0-0
1,2,1,host,1,0,host,02:43:21,NaN,221.029999,1-0
2,3,1,guest,2,0,guest,02:47:02,NaN,202.399994,2-0
3,4,1,host,2,1,host,02:50:24,NaN,181.970001,2-1
4,5,1,guest,3,1,host,02:53:26,NaN,210.300003,3-1

In [18]:
swing_data_games = swing_data_games[['Game', 'gameScore']]

In [19]:
swing_data = pd.merge(swing_data, swing_data_games, on="Game")

In [20]:
swing_data

               Player  Shot             Type     Stroke     Spin  Speed (MPH)  \
0       Luca Staeheli     1      first_serve      Serve    Slice   118.400520
1       Luca Staeheli     1     second_serve      Serve    Slice    76.265121
2    Aadarsh Tiprathi     2    second_return   Backhand  Topspin    54.827156
3       Luca Staeheli     3   serve_plus_one   Backhand  Topspin    60.095497
4    Aadarsh Tiprathi     4  return_plus_one   Backhand  Topspin    57.061077
5       Luca Staeheli     5          in_play   Forehand  Topspin    53.422405
6    Aadarsh Tiprathi     6          in_play   Forehand  Topspin    64.707542
7       Luca Staeheli     7          in_play   Forehand  Topspin    57.150948
8    Aadarsh Tiprathi     8          in_play   Forehand  Topspin    67.915596
9       Luca Staeheli     9          in_play   Forehand  Topspin    47.245522
10   Aadarsh Tiprathi    10          in_play   Backhand    Slice    38.555569
11      Luca Staeheli     1      first_serve      Serve    Slice    92.253929
12   Aadarsh Tiprathi     2     first_return   Forehand  Topspin    51.220169
13      Luca Staeheli     3   serve_plus_one   Forehand  Topspin    36.577976
14      Luca Staeheli     1      first_serve      Serve    Slice   105.212898
15   Aadarsh Tiprathi     2     first_return   Backhand     Flat    29.418373
16   Aadarsh Tiprathi     3   serve_plus_one  FH Volley     Flat    18.186579
17      Luca Staeheli     1      first_serve      Serve    Slice   100.107254
18   Aadarsh Tiprathi     2     first_return   Backhand     Flat    37.807911
19      Luca Staeheli     3   serve_plus_one   Backhand  Topspin    54.442429
20   Aadarsh Tiprathi     4  return_plus_one   Forehand  Topspin    38.340214
21      Luca Staeheli     5          in_play   Forehand  Topspin    68.766663
22      Luca Staeheli     1      first_serve      Serve    Slice    48.036575
23      Luca Staeheli     1     second_serve      Serve    Slice    84.833031
24   Aadarsh Tiprathi     2    second_return   Forehand     Flat    51.610207
25      Luca Staeheli     3   serve_plus_one   Forehand  Topspin    61.274822
26   Aadarsh Tiprathi     4  return_plus_one   Forehand  Topspin    63.869610
27   Aadarsh Tiprathi     1      first_serve      Serve    Slice   111.820526
28      Luca Staeheli     2     first_return   Backhand    Slice    31.530741
29   Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    79.372902
30      Luca Staeheli     4  return_plus_one   Backhand  Topspin    40.116558
31   Aadarsh Tiprathi     5          in_play  FH Volley     Flat    23.382744
32   Aadarsh Tiprathi     1      first_serve      Serve     Flat    98.727882
33      Luca Staeheli     2     first_return   Forehand  Topspin    52.709641
34   Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    46.601204
35      Luca Staeheli     4  return_plus_one   Forehand     Flat    59.114990
36   Aadarsh Tiprathi     5          in_play   Forehand  Topspin    58.398331
37      Luca Staeheli     6          in_play   Forehand     Flat    78.924599
38   Aadarsh Tiprathi     7          in_play   Forehand  Topspin    59.723789
39      Luca Staeheli     8          in_play   Forehand  Topspin    66.651627
40   Aadarsh Tiprathi     9          in_play   Forehand     Flat    54.234238
41      Luca Staeheli    10          in_play   Forehand  Topspin    46.774864
42   Aadarsh Tiprathi     1      first_serve      Serve    Slice    55.368778
43   Aadarsh Tiprathi     1     second_serve      Serve     Flat    71.111176
44      Luca Staeheli     2    second_return   Backhand  Topspin    71.640923
45   Aadarsh Tiprathi     3   serve_plus_one   Backhand     Flat    41.034534
46   Aadarsh Tiprathi     1      first_serve      Serve     Flat    89.704163
47      Luca Staeheli     2     first_return   Backhand  Topspin    28.473553
48   Aadarsh Tiprathi     1      first_serve      Serve    Slice   108.291054
49      Luca Staeheli     2     first_return   Forehand     Flat    49.066475
50   Aadarsh Tiprathi     1      first_serve      Serve     Flat   102.733032
51   Aadarsh Tiprathi     1     second_serve      Serve     Flat    71.639969
52      Luca Staeheli     2    second_return   Forehand  Topspin    76.672874
53   Aadarsh Tiprathi     3   serve_plus_one   Forehand     Flat    48.664196
54      Luca Staeheli     4  return_plus_one   Forehand  Topspin    58.800064
55   Aadarsh Tiprathi     5          in_play   Forehand  Topspin    58.007431
56      Luca Staeheli     6          in_play   Backhand  Topspin    53.094109
57   Aadarsh Tiprathi     7          in_play   Backhand     Flat    59.201557
58      Luca Staeheli     8          in_play   Backhand     Flat    63.984577
59   Aadarsh Tiprathi     9          in_play   Forehand  Topspin    55.869762
60      Luca Staeheli    10          in_play   Backhand  Topspin    61.131458
61   Aadarsh Tiprathi    11          in_play   Backhand     Flat    56.295582
62      Luca Staeheli    12          in_play   Backhand     Flat    86.347710
63   Aadarsh Tiprathi    13          in_play   Forehand  Topspin    60.770454
64      Luca Staeheli    14          in_play   Forehand     Flat    56.106476
65   Aadarsh Tiprathi    15          in_play   Forehand     Flat    69.011993
66      Luca Staeheli    16          in_play   Forehand     Flat    60.108212
67   Aadarsh Tiprathi    17          in_play   Forehand  Topspin    65.056999
68      Luca Staeheli    18          in_play   Forehand  Topspin    59.946697
69   Aadarsh Tiprathi    19          in_play   Forehand  Topspin    58.454376
70      Luca Staeheli    20          in_play   Backhand    Slice    47.192978
71   Aadarsh Tiprathi    21          in_play   Forehand  Topspin    49.141788
72      Luca Staeheli    22          in_play   Forehand  Topspin    69.754974
73   Aadarsh Tiprathi    23          in_play   Forehand     Flat    53.320465
74      Luca Staeheli    24          in_play   Forehand     Flat    70.487526
75   Aadarsh Tiprathi    25          in_play   Forehand     Flat    35.546494
76   Aadarsh Tiprathi     1      first_serve      Serve     Flat   118.015244
77      Luca Staeheli     2     first_return   Forehand  Topspin    52.392502
78   Aadarsh Tiprathi     3   serve_plus_one   Backhand  Topspin    54.535427
79      Luca Staeheli     4  return_plus_one   Forehand  Topspin    63.702755
80   Aadarsh Tiprathi     5          in_play   Forehand     Flat    59.497463
81      Luca Staeheli     6          in_play   Forehand  Topspin    50.156399
82   Aadarsh Tiprathi     7          in_play   Forehand  Topspin    56.949978
83      Luca Staeheli     1      first_serve      Serve     Flat    54.450356
84      Luca Staeheli     1     second_serve      Serve    Slice    78.729454
85   Aadarsh Tiprathi     2    second_return   Backhand     Flat    45.094051
86      Luca Staeheli     3   serve_plus_one   Forehand  Topspin    53.951550
87   Aadarsh Tiprathi     4  return_plus_one   Forehand  Topspin    61.575722
88      Luca Staeheli     1      first_serve      Serve     Flat   101.417473
89   Aadarsh Tiprathi     2     first_return   Backhand  Topspin    50.759090
90      Luca Staeheli     3   serve_plus_one   Backhand     Flat    29.519285
91   Aadarsh Tiprathi     4  return_plus_one   Backhand  Topspin    30.354078
92      Luca Staeheli     1      first_serve      Serve     Flat    97.548149
93   Aadarsh Tiprathi     2     first_return   Backhand     Flat    50.365536
94      Luca Staeheli     3   serve_plus_one   Forehand     Flat    76.324745
95   Aadarsh Tiprathi     4  return_plus_one   Forehand     Flat    53.274902
96      Luca Staeheli     1      first_serve      Serve     Flat    91.832710
97   Aadarsh Tiprathi     2     first_return   Backhand  Topspin    42.241470
98      Luca Staeheli     3   serve_plus_one   Forehand  Topspin    67.163246
99   Aadarsh Tiprathi     4  return_plus_one   Forehand  Topspin    34.870491
100     Luca Staeheli     5          in_play  BH Volley     Flat    23.382744
101  Aadarsh Tiprathi     1      first_serve      Serve    Slice    92.900757
102     Luca Staeheli     2     first_return   Forehand     Flat    33.958698
103  Aadarsh Tiprathi     1      first_serve      Serve     Flat    98.814537
104     Luca Staeheli     2     first_return   Backhand     Flat    47.898804
105  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    58.450504
106     Luca Staeheli     4  return_plus_one   Forehand  Topspin    47.320232
107  Aadarsh Tiprathi     5          in_play   Forehand  Topspin    41.150944
108  Aadarsh Tiprathi     1      first_serve      Serve     Flat    93.138565
109  Aadarsh Tiprathi     1      first_serve      Serve     Flat    95.823532
110     Luca Staeheli     2     first_return   Forehand     Flat    51.793503
111  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    67.733742
112     Luca Staeheli     4  return_plus_one   Backhand  Topspin    60.864891
113  Aadarsh Tiprathi     5          in_play   Forehand  Topspin    75.565140
114     Luca Staeheli     6          in_play   Forehand  Topspin    56.401001
115  Aadarsh Tiprathi     7          in_play   Forehand  Topspin    69.478371
116     Luca Staeheli     8          in_play   Forehand     Flat    42.164837
117  Aadarsh Tiprathi     9          in_play   Forehand  Topspin    57.084297
118  Aadarsh Tiprathi     1      first_serve      Serve     Flat    52.872044
119  Aadarsh Tiprathi     1     second_serve      Serve     Flat    75.554558
120     Luca Staeheli     2    second_return   Forehand     Flat    35.631302
121  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    53.925255
122     Luca Staeheli     4  return_plus_one   Backhand    Slice    40.019306
123  Aadarsh Tiprathi     5          in_play   Backhand     Flat    42.226608
124     Luca Staeheli     6          in_play   Forehand     Flat    43.372612
125     Luca Staeheli     1      first_serve      Serve    Slice   103.489250
126  Aadarsh Tiprathi     2     first_return   Backhand  Topspin    47.778629
127     Luca Staeheli     3   serve_plus_one   Forehand  Topspin    61.220558
128  Aadarsh Tiprathi     4  return_plus_one   Backhand     Flat    68.690598
129     Luca Staeheli     5          in_play  FH Volley     Flat    19.918634
130     Luca Staeheli     1      first_serve      Serve    Slice    50.255051
131     Luca Staeheli     1     second_serve      Serve    Slice    76.836807
132  Aadarsh Tiprathi     2    second_return   Backhand  Topspin    53.287292
133     Luca Staeheli     3   serve_plus_one   Backhand     Flat    71.552605
134  Aadarsh Tiprathi     4  return_plus_one   Forehand     Flat    27.810757
135     Luca Staeheli     1      first_serve      Serve     Flat    99.892632
136  Aadarsh Tiprathi     2     first_return   Backhand     Flat    61.564095
137     Luca Staeheli     3   serve_plus_one   Forehand  Topspin    66.215721
138  Aadarsh Tiprathi     4  return_plus_one   Forehand  Topspin    52.752201
139     Luca Staeheli     5          in_play   Backhand  Topspin    57.731712
140  Aadarsh Tiprathi     6          in_play   Backhand  Topspin    73.777626
141     Luca Staeheli     7          in_play   Forehand  Topspin    51.341576
142  Aadarsh Tiprathi     8          in_play   Forehand  Topspin    66.879875
143     Luca Staeheli     9          in_play   Backhand     Flat    44.070309
144     Luca Staeheli     1      first_serve      Serve    Slice   120.719803
145  Aadarsh Tiprathi     2     first_return   Backhand  Topspin    56.107914
146     Luca Staeheli     3   serve_plus_one   Forehand  Topspin    68.536972
147  Aadarsh Tiprathi     4  return_plus_one   Forehand  Topspin    51.813778
148     Luca Staeheli     5          in_play   Forehand  Topspin    54.508804
149  Aadarsh Tiprathi     6          in_play   Backhand  Topspin    61.830139
150     Luca Staeheli     7          in_play   Forehand  Topspin    57.449249
151  Aadarsh Tiprathi     8          in_play   Backhand     Flat    49.187710
152     Luca Staeheli     9          in_play   Forehand  Topspin    71.010666
153  Aadarsh Tiprathi    10          in_play   Forehand  Topspin    58.340706
154     Luca Staeheli    11          in_play   Forehand  Topspin    35.744129
155     Luca Staeheli     1      first_serve      Serve     Flat    96.283882
156  Aadarsh Tiprathi     2     first_return   Backhand     Flat    56.131428
157     Luca Staeheli     3   serve_plus_one   Forehand  Topspin    59.996002
158  Aadarsh Tiprathi     4  return_plus_one   Backhand  Topspin    59.902779
159     Luca Staeheli     5          in_play   Forehand  Topspin    56.594830
160  Aadarsh Tiprathi     6          in_play   Backhand     Flat    57.173027
161     Luca Staeheli     7          in_play   Backhand     Flat    63.835960
162  Aadarsh Tiprathi     8          in_play   Backhand     Flat    58.588478
163     Luca Staeheli     9          in_play   Backhand     Flat    60.314220
164  Aadarsh Tiprathi    10          in_play   Backhand  Topspin    48.339024
165  Aadarsh Tiprathi     1      first_serve      Serve    Slice    93.627411
166  Aadarsh Tiprathi     1     second_serve      Serve    Slice    77.754898
167     Luca Staeheli     2    second_return   Forehand  Topspin    78.189583
168  Aadarsh Tiprathi     1      first_serve      Serve     Flat   101.311134
169     Luca Staeheli     2     first_return   Forehand     Flat    45.450680
170  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    66.389359
171     Luca Staeheli     4  return_plus_one   Forehand    Slice    34.874592
172  Aadarsh Tiprathi     1      first_serve      Serve    Slice    95.563789
173     Luca Staeheli     2     first_return   Forehand     Flat    54.398960
174  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    61.898113
175     Luca Staeheli     4  return_plus_one   Backhand     Flat    44.997646
176  Aadarsh Tiprathi     5          in_play   Forehand  Topspin    63.646976
177     Luca Staeheli     6          in_play   Forehand  Topspin    58.338413
178  Aadarsh Tiprathi     7          in_play   Forehand     Flat    65.457062
179     Luca Staeheli     8          in_play   Backhand    Slice    29.955021
180  Aadarsh Tiprathi     9          in_play   Forehand    Slice    35.955051
181  Aadarsh Tiprathi     1      first_serve      Serve     Flat   103.867752
182     Luca Staeheli     2     first_return   Backhand  Topspin    52.277920
183  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    57.290291
184     Luca Staeheli     4  return_plus_one   Forehand  Topspin    43.369171
185  Aadarsh Tiprathi     5          in_play  FH Volley     Flat    10.931062
186  Aadarsh Tiprathi     1      first_serve      Serve    Slice    55.675961
187  Aadarsh Tiprathi     1     second_serve      Serve    Slice    76.248512
188     Luca Staeheli     2    second_return   Forehand     Flat    63.979454
189  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    58.595554
190     Luca Staeheli     4  return_plus_one   Backhand    Slice    34.771984
191  Aadarsh Tiprathi     5          in_play  FH Volley     Flat    22.188662
192     Luca Staeheli     1      first_serve      Serve     Flat   101.819679
193     Luca Staeheli     1     second_serve      Serve     Flat    59.641651
194  Aadarsh Tiprathi     2    second_return   Forehand     Flat    47.677567
195     Luca Staeheli     3   serve_plus_one   Backhand  Topspin    61.664478
196  Aadarsh Tiprathi     4  return_plus_one   Backhand  Topspin    53.791447
197     Luca Staeheli     5          in_play   Backhand     Flat    60.801865
198     Luca Staeheli     1      first_serve      Serve     Flat    96.816017
199     Luca Staeheli     1     second_serve      Serve    Slice    74.302750
200  Aadarsh Tiprathi     2    second_return   Backhand  Topspin    31.993559
201     Luca Staeheli     3   serve_plus_one   Backhand     Flat    74.241028
202  Aadarsh Tiprathi     4  return_plus_one   Forehand    Slice    38.589664
203     Luca Staeheli     5          in_play   Forehand  Topspin    69.764534
204  Aadarsh Tiprathi     6          in_play   Backhand    Slice    49.006809
205     Luca Staeheli     7          in_play  FH Volley     Flat    19.052607
206     Luca Staeheli     1      first_serve      Serve    Slice    89.089836
207  Aadarsh Tiprathi     2     first_return   Backhand  Topspin    50.370659
208     Luca Staeheli     3   serve_plus_one   Forehand  Topspin    53.450417
209  Aadarsh Tiprathi     4  return_plus_one   Forehand     Flat    46.843029
210     Luca Staeheli     1      first_serve      Serve     Flat    98.190430
211     Luca Staeheli     1     second_serve      Serve    Slice    70.489502
212  Aadarsh Tiprathi     2    second_return   Backhand     Flat    60.135651
213     Luca Staeheli     3   serve_plus_one   Backhand    Slice    43.868301
214  Aadarsh Tiprathi     4  return_plus_one   Forehand  Topspin    58.955135
215     Luca Staeheli     5          in_play   Backhand     Flat    74.126541
216  Aadarsh Tiprathi     6          in_play   Backhand  Topspin    60.959473
217     Luca Staeheli     7          in_play   Forehand  Topspin    50.494213
218  Aadarsh Tiprathi     8          in_play   Forehand     Flat    71.308121
219     Luca Staeheli     9          in_play   Backhand    Slice    38.494801
220  Aadarsh Tiprathi    10          in_play   Forehand    Slice    30.582502
221     Luca Staeheli    11          in_play   Forehand  Topspin    35.619335
222     Luca Staeheli     1      first_serve      Serve    Slice    87.914452
223  Aadarsh Tiprathi     2     first_return   Forehand  Topspin    33.423767
224     Luca Staeheli     3   serve_plus_one   Forehand    Slice    90.413277
225  Aadarsh Tiprathi     4  return_plus_one   Forehand     Flat    40.255886
226     Luca Staeheli     5          in_play   Backhand     Flat    64.200966
227  Aadarsh Tiprathi     6          in_play   Forehand  Topspin    66.399689
228     Luca Staeheli     7          in_play   Forehand  Topspin    63.141773
229  Aadarsh Tiprathi     8          in_play   Forehand  Topspin    57.685429
230     Luca Staeheli     9          in_play   Forehand  Topspin    52.601429
231  Aadarsh Tiprathi    10          in_play   Forehand  Topspin    72.764244
232     Luca Staeheli     1      first_serve      Serve     Flat    82.850494
233     Luca Staeheli     1     second_serve      Serve     Flat    90.412117
234  Aadarsh Tiprathi     2    second_return   Forehand     Flat    37.465412
235     Luca Staeheli     3   serve_plus_one   Forehand  Topspin    60.369862
236  Aadarsh Tiprathi     4  return_plus_one   Backhand  Topspin    53.343105
237     Luca Staeheli     5          in_play  FH Volley     Flat    22.516716
238     Luca Staeheli     1      first_serve      Serve     Flat    92.844536
239  Aadarsh Tiprathi     1     second_serve      Serve     Flat    75.353920
240     Luca Staeheli     2    second_return   Forehand     Flat    58.060566
241  Aadarsh Tiprathi     3   serve_plus_one   Forehand  Topspin    54.777813
242     Luca Staeheli     4  return_plus_one   Backhand  Topspin    58.450573
243  Aadarsh Tiprathi     5          in_play   Forehand  Topspin    53.304150
244     Luca Staeheli     6          in_play   Forehand  Topspin    54.299690
245  Aadarsh Tiprathi     7          in_play   Forehand  Topspin    63.345737
246     Luca Staeheli     8          in_play   Backhand  Topspin    53.972321
247  Aadarsh Tiprathi     9          in_play   Forehand     Flat    25.055004
248     Luca Staeheli    10          in_play   Forehand  Topspin    71.707085
249  Aadarsh Tiprathi     1      first_serve      Serve     Flat    84.169571
250  Aadarsh Tiprathi     1      first_serve      Serve     Flat    68.875916
251  Aadarsh Tiprathi     1      first_serve      Serve     Flat    98.266808
252     Luca Staeheli     2     first_return   Backhand  Topspin    52.088787
253  Aadarsh Tiprathi     3   serve_plus_one   Backhand  Topspin    54.819851
254     Luca Staeheli     4  return_plus_one   Forehand  Topspin    59.780529

### Create shot data csv

In [21]:
# Check existing columns
swing_data.columns

Index(['Player', 'Shot', 'Type', 'Stroke', 'Spin', 'Speed (MPH)', 'Point',
       'Game', 'Set', 'Bounce Depth', 'Bounce Zone', 'Bounce Side',
       'Bounce (x)', 'Bounce (y)', 'Hit Depth', 'Hit Zone', 'Hit Side',
       'Hit (x)', 'Hit (y)', 'Hit (z)', 'Direction', 'Result', 'Favorited',
       'Start Time', 'Video Time', 'pointScore', 'isBreakPoint', 'gameScore'],
      dtype='object')

In [22]:
swing_data.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time,pointScore,isBreakPoint,gameScore
0,Luca Staeheli,1,first_serve,Serve,Slice,118.400520,1,1,1,short,ad,far,0.378870,16.762121,out,deuce,near,1.135853,-0.554549,2.673766,down the T,Out,False,21:27:07,17.92,0-0,,0-0
1,Luca Staeheli,1,second_serve,Serve,Slice,76.265121,1,1,1,short,deuce,far,-0.731950,16.227081,deep,deuce,near,0.803059,-0.379706,2.749103,down the T,In,False,21:27:17,27.41,0-0,,0-0
2,Aadarsh Tiprathi,2,second_return,Backhand,Topspin,54.827156,1,1,1,short,ad,near,-0.973862,7.295816,deep,deuce,far,-1.363457,24.678232,1.643152,inside in,In,False,21:27:18,28.32,0-0,,0-0
3,Luca Staeheli,3,serve_plus_one,Backhand,Topspin,60.095497,1,1,1,deep,ad,far,2.046510,20.453445,deep,ad,near,-0.583427,0.621297,0.803284,cross court,In,False,21:27:19,29.57,0-0,,0-0
4,Aadarsh Tiprathi,4,return_plus_one,Backhand,Topspin,57.061077,1,1,1,deep,deuce,near,0.761086,1.642498,out,ad,far,2.400083,25.378126,1.205338,down the line,In,False,21:27:20,30.76,0-0,,0-0

In [23]:
# add in all desired column labels, with swingvision labels at end

columm_names = (['pointScore', 'gameScore', 'setScore', 'isPointStart', 
                                         'pointStartTime', 'isPointEnd', 'pointEndTime','pointNumber',
                                         'isBreakPoint','shotInRally','side','serverName',
                                         'serverFarNear','firstServeIn','firstServeZone',
                                         'firstServeXCoord','firstServeYCoord',
                                         'secondServeIn','secondServeZone','secondServeXCoord',
                                         'secondServeYCoord','isAce','shotContactX',
                                         'shotContactY','shotDirection','shotFhBh',
                                         'isSlice','isVolley','isOverhead','isApproach','isDropshot',
                                         'isExcitingPoint','atNetPlayer1','atNetPlayer2','isLob',
                                         'shotLocationX','shotLocationY','isWinner','isErrorWideR', 'isErrorWideL',
                                         'isErrorNet','isErrorLong','clientTeam',
                                         'Date', 'Division', 'Event', 'lineupPosition','matchDetails',
                                         'matchVenue' , 'opponentTeam', 
                                         'player1Name', 'player2Name','player1Hand','player2Hand',
                                        'Round','Surface','Notes'])

shot_data = pd.DataFrame(columns=columm_names)
shot_data

Empty DataFrame
Columns: [pointScore, gameScore, setScore, isPointStart, pointStartTime, isPointEnd, pointEndTime, pointNumber, isBreakPoint, shotInRally, side, serverName, serverFarNear, firstServeIn, firstServeZone, firstServeXCoord, firstServeYCoord, secondServeIn, secondServeZone, secondServeXCoord, secondServeYCoord, isAce, shotContactX, shotContactY, shotDirection, shotFhBh, isSlice, isVolley, isOverhead, isApproach, isDropshot, isExcitingPoint, atNetPlayer1, atNetPlayer2, isLob, shotLocationX, shotLocationY, isWinner, isErrorWideR, isErrorWideL, isErrorNet, isErrorLong, clientTeam, Date, Division, Event, lineupPosition, matchDetails, matchVenue, opponentTeam, player1Name, player2Name, player1Hand, player2Hand, Round, Surface, Notes]
Index: []

### Score Columns

In [24]:
shot_data['pointScore'] = swing_data['pointScore']
shot_data['gameScore'] = swing_data['gameScore']

In [25]:
shot_data.head(50)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
0,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,15-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,15-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,15-0,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,15-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,30-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,30-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,30-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,30-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,30-15,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,30-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,30-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,30-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,30-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,30-30,0-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,30-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,30-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,30-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,40-40,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,0-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,0-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,0-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,15-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,15-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,30-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,30-0,1-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### isPointStart and isPointEnd columns

In [26]:
def assign_pointstart(x):
    if (x == 'first_serve') | (x == 'second_serve'):
        return 1
    
    return ''

shot_data['isPointStart'] = swing_data['Type'].apply(assign_pointstart)


index_list = []

for i in swing_data['Point'].unique().tolist():
    last_point_index = swing_data[swing_data['Point'] == i].index[-1]
    index_list.append(last_point_index)
    
shot_data.loc[index_list,'isPointEnd'] = 1
shot_data['isPointEnd'] = shot_data['isPointEnd'].fillna('')

### pointStartTime and pointEndTime Columns

In [27]:
# Grab the initial time
match_start_time = re.split(":", swing_data["Start Time"][0])

for i in range(len(swing_data)): # converting into milliseconds
    time = re.split(":", swing_data["Start Time"][i])
    shot_data.loc[i,'pointStartTime'] = ((int(time[0]) - int(match_start_time[0])) *  3600000
                                       + (int(time[1]) - int(match_start_time[1])) *  60000
                                       + (int(time[2]) - int(match_start_time[2])) *  1000)
    
# Assigns last shot time to pointEndTime column
shot_data['pointEndTime'] = np.where(shot_data['isPointEnd'] == 1, shot_data['pointStartTime'], '')

### pointNumber Column

In [28]:
shot_data['pointNumber'] = swing_data['Point']

### isBreakPoint Column

In [29]:
shot_data['isBreakPoint'] = swing_data['isBreakPoint']

### shotInRally column

In [30]:
shot_data.shotInRally = swing_data.Shot

### side column
#### WARNING: outputs 'Center' and we don't have that metric

In [31]:
def side(x):
    if 'deuce' in x:
        return 'Deuce'
    elif 'ad' in x:
        return 'Ad'
    elif 'center_line' in x:
        return 'Center'
    else:
        return ''

shot_data['side'] = swing_data['Hit Zone'].apply(side)

### Players

In [32]:
# ucla roster 23-24 men and womens
ucla_roster_23 = ["Gianluca Ballotta", 
                   "Jeffrey Fradkin", 
                   "Alexander Hoogmartens",
                   "Spencer Johnson",
                   "Stefan Leustian",
                   "Timothy Li",
                   "Govind Nanda",
                   "Jorge Plans Gonzalez",
                   "Giacomo Revelli",
                   "Aadarsh Tripathi",
                   "Emon van Loben Sels",
                   "Azuma Visaya",
                   
                   "Tian Fangran",
                   "Bianca Fernandez",
                   "Ahmani Guichard",
                   "Kimmi Hance",
                   "Mia Jovic",
                   "Anne-Christine Lutkemeyer",
                   "Vanessa Ong",
                   "Sasha Vagramov",
                   "Elise Wagle"]

In [33]:
# list of names who are playing in match
players = swing_data["Player"].unique()

# checks which one is UCLA player
is_ucla_player = [any([name in roster_name for roster_name in ucla_roster_23]) for name in players]

In [34]:
# assigns ucla player to player 1, and non ucla to player 2
shot_data.loc[0, "player1Name"] = players[is_ucla_player]
shot_data.loc[0, "player2Name"] = players[np.invert(is_ucla_player)]

ValueError: Must have equal len keys and value when setting with an iterable

### serverName Column

In [ ]:
def assign_server_name(stroke, server):
    if stroke != 'Serve':
        return ''
    
    if server.startswith(players[is_ucla_player][0]):
        return 'Player1'
    elif server.startswith(players[np.invert(is_ucla_player)][0]):
        return 'Player2'
    
shot_data['serverName'] = swing_data.apply(lambda x: assign_server_name(x['Stroke'], x['Player']), axis=1)
shot_data['serverName'].replace(['', 'na'], pd.NaT, inplace=True)
shot_data['serverName'] = shot_data['serverName'].ffill()

### serverFarNear Column

In [35]:
shot_data.serverFarNear = np.where((swing_data.Stroke == 'Serve'), np.where(swing_data['Hit Side'] == 'far', 'Far', 'Near'), '')
shot_data['serverFarNear'].replace(['', 'na'], pd.NaT, inplace=True)
shot_data['serverFarNear'] = shot_data['serverFarNear'].ffill()

### firstServeIn and secondServeIn Columns

In [41]:
shot_data.firstServeIn = np.where((swing_data.Type == 'first_serve'),np.where((shot_data.isPointStart == 1) & (swing_data['Result'] == 'In'), 1, 0), np.nan)
shot_data.secondServeIn =np.where((swing_data.Type == 'second_serve') & (shot_data.isPointStart == 1), np.where(swing_data['Result'] == 'In', 1,0), np.nan)

### SwingVision Coord Transformation
court coordinates
swing vision - meters, near side center marks (0,0)
singles court x [-4.1148, 4.1148], y [0, 23.7744]
doubles court x [-5.485, 5.485]

our coordinates - center of net (0,0)
singles court x [-157.5, 157.5], y [-455, 455]

shot_x = (157.5/4.1148) * swing_x
shot_y = (455/11.8872) * swing_y + 455
ratio = 38.2764654418

### firstServeXCoord, firstYServeYCoord, secondServeXCoord, and secondServeyCoord Columns

In [42]:
def first_serve_x_coordinates(stroke, x):
    if stroke == 'first_serve':
        return x * 38.2764654418
    else:
        return np.nan

def first_serve_y_coordinates(stroke, y):
    if stroke == 'first_serve':
        return (y - 11.8872) * 38.2764654418
    else:
        return np.nan
    
shot_data['firstServeXCoord'] = swing_data.apply(lambda row: first_serve_x_coordinates(row['Type'], row['Bounce (x)']), axis=1)
shot_data['firstServeYCoord'] = swing_data.apply(lambda row: first_serve_y_coordinates(row['Type'], row['Bounce (y)']), axis=1)


def second_serve_x_coordinates(stroke, x):
    if stroke == 'second_serve':
        return x * 38.2764654418
    else:
        return np.nan

def second_serve_y_coordinates(stroke, y):
    if stroke == 'second_serve':
        return (y - 11.8872) * 38.2764654418
    else:
        return np.nan
    
shot_data['secondServeXCoord'] = swing_data.apply(lambda row: second_serve_x_coordinates(row['Type'], row['Bounce (x)']), axis=1)
shot_data['secondServeYCoord'] = swing_data.apply(lambda row: second_serve_y_coordinates(row['Type'], row['Bounce (y)']), axis=1)

### firstServeZone and secondServeZone Columns
- serving zones: T, Body, Wide
- Wide: x in [-inf, -105] u [105, inf]
- Body: x in [-105, -52.5] u [52.5, 105]
- T: x in [-52.5, 52.5]

In [43]:
def label_zone(x_coord):
    if x_coord != '':
        x_coord = float(x_coord)
        if (x_coord < -105) | (x_coord > 105):
            return 'Wide'
        elif (-105 <= x_coord <= -52.5) | (52.5 <= x_coord <= 105):
            return 'Body'
        elif -52.5 < x_coord < 52.5:
            return 'T'
    return ''

# convert x coord to serve zone
shot_data.firstServeZone = shot_data.firstServeXCoord.apply(label_zone)
shot_data.secondServeZone = shot_data.secondServeXCoord.apply(label_zone)

In [44]:
shot_data.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
0,0-0,0-0,NaN,1,0,,,1,,1,Deuce,Player2,Near,1.0,Body,-68.760378,212.123693,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Elise Wagle,Matka Komac,NaN,NaN,NaN,NaN,NaN
1,0-0,0-0,NaN,,2000,,,1,,2,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-0,0-0,NaN,,3000,,,1,,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,NaN,,5000,,,1,,4,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-0,0-0,NaN,,7000,,,1,,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### isAce Column
- WARNING: Not accurate
- FIX: counts double faults as aces

In [45]:
shot_data['isAce'] = np.where((swing_data.Stroke == 'Serve') & 
                              (shot_data.isPointEnd == 1) & 
                              (shot_data.secondServeIn != 0), 1, np.nan)

In [46]:
shot_data[460:600]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
460,15-15,1-1,NaN,,4099000,,,90,,4,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,15-15,1-1,NaN,,4101000,1,4101000,90,,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462,15-30,1-1,NaN,1,4126000,1,4126000,91,,1,Ad,Player1,Near,0.0,Body,100.345505,-29.805616,NaN,,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
463,30-30,1-1,NaN,1,4144000,,,92,,1,Deuce,Player1,Near,0.0,Wide,111.827335,242.937587,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
464,30-30,1-1,NaN,1,4181000,,,92,,1,Deuce,Player1,Near,0.0,T,-29.876044,-11.077400,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
465,30-30,1-1,NaN,1,4195000,,,92,,1,Deuce,Player1,Near,NaN,,NaN,NaN,1.0,Body,-68.659941,197.761253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,30-30,1-1,NaN,,4196000,,,92,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,30-30,1-1,NaN,,4197000,,,92,,3,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,30-30,1-1,NaN,,4199000,,,92,,4,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,30-30,1-1,NaN,,4200000,,,92,,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470,30-30,1-1,NaN,,4203000,,,92,,6,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,30-30,1-1,NaN,,4205000,1,4205000,92,,7,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,30-40,1-1,NaN,1,4234000,,,93,1,1,Ad,Player1,Near,1.0,Body,93.744691,234.644111,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
473,30-40,1-1,NaN,,4235000,,,93,1,2,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,30-40,1-1,NaN,,4237000,,,93,1,3,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,30-40,1-1,NaN,,4238000,,,93,1,4,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,30-40,1-1,NaN,,4240000,,,93,1,5,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,30-40,1-1,NaN,,4241000,1,4241000,93,1,6,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,40-40,1-1,NaN,1,4274000,,,94,1,1,Deuce,Player1,Near,1.0,T,-30.099809,227.488785,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,40-40,1-1,NaN,,4275000,1,4275000,94,1,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,0-0,2-1,NaN,1,4386000,,,95,,1,Deuce,Player2,Near,0.0,Body,-65.745839,287.336067,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,0-0,2-1,NaN,1,4397000,1,4397000,95,,1,Deuce,Player2,Near,NaN,,NaN,NaN,0.0,Body,-59.654254,-237.880960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,0-15,2-1,NaN,1,4422000,,,96,,1,Ad,Player2,Near,1.0,Body,91.130906,238.491049,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,0-15,2-1,NaN,,4423000,,,96,,2,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,0-15,2-1,NaN,,4425000,,,96,,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,0-15,2-1,NaN,,4426000,,,96,,4,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,0-15,2-1,NaN,,4428000,,,96,,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,0-15,2-1,NaN,,4429000,1,4429000,96,,6,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,15-15,2-1,NaN,1,4462000,,,97,,1,Deuce,Player2,Near,0.0,Wide,-156.391322,246.481452,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489,15-15,2-1,NaN,,4463000,,,97,,2,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,15-15,2-1,NaN,,4465000,,,97,,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,15-15,2-1,NaN,,4466000,,,97,,4,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,15-15,2-1,NaN,,4467000,,,97,,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,15-15,2-1,NaN,,4469000,1,4469000,97,,6,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,30-15,2-1,NaN,1,4493000,,,98,,1,Ad,Player2,Near,0.0,Wide,106.308749,-47.522069,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,30-15,2-1,NaN,1,4503000,,,98,,1,Ad,Player2,Near,NaN,,NaN,NaN,1.0,Body,54.146233,220.519751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,30-15,2-1,NaN,,4504000,,,98,,2,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,30-15,2-1,NaN,,4506000,1,4506000,98,,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,30-30,2-1,NaN,1,4543000,,,99,,1,Deuce,Player2,Near,0.0,Wide,-179.648753,306.513572,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,30-30,2-1,NaN,1,4556000,,,99,,1,Deuce,Player2,Near,NaN,,NaN,NaN,0.0,Wide,-115.359640,245.127690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,30-30,2-1,NaN,,4557000,,,99,,2,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,30-30,2-1,NaN,,4559000,1,4559000,99,,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,30-40,2-1,NaN,1,4596000,,,100,1,1,Ad,Player2,Near,0.0,T,17.013238,304.662790,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,30-40,2-1,NaN,1,4608000,,,100,1,1,Ad,Player2,Near,NaN,,NaN,NaN,0.0,Body,73.502488,257.132376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,30-40,2-1,NaN,,4609000,,,100,1,2,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,30-40,2-1,NaN,,4610000,,,100,1,3,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,30-40,2-1,NaN,,4612000,,,100,1,4,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,30-40,2-1,NaN,,4613000,,,100,1,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,30-40,2-1,NaN,,4615000,,,100,1,6,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
509,30-40,2-1,NaN,,4616000,,,100,1,7,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,30-40,2-1,NaN,,4617000,,,100,1,8,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,30-40,2-1,NaN,,4619000,,,100,1,9,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,30-40,2-1,NaN,,4628000,1,4628000,100,1,10,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,0-0,3-1,NaN,1,4657000,,,101,,1,Deuce,Player1,Far,0.0,Wide,152.989578,-248.123704,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,0-0,3-1,NaN,1,4669000,,,101,,1,Deuce,Player1,Far,NaN,,NaN,NaN,1.0,Body,82.982114,-152.957847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
515,0-0,3-1,NaN,,4670000,,,101,,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,0-0,3-1,NaN,,4671000,,,101,,3,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,0-0,3-1,NaN,,4672000,,,101,,4,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,0-0,3-1,NaN,,4674000,,,101,,5,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,0-0,3-1,NaN,,4675000,1,4675000,101,,6,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,15-0,3-1,NaN,1,4698000,,,102,,1,Ad,Player1,Far,1.0,Wide,-142.610110,-164.880047,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,15-0,3-1,NaN,,4699000,,,102,,2,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
522,15-0,3-1,NaN,,4701000,,,102,,3,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,15-0,3-1,NaN,,4702000,1,4702000,102,,4,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,30-0,3-1,NaN,1,4725000,,,103,,1,Deuce,Player1,Far,1.0,Body,68.381594,-205.636827,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525,30-0,3-1,NaN,,4726000,,,103,,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,30-0,3-1,NaN,,4728000,,,103,,3,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,30-0,3-1,NaN,,4729000,1,4729000,103,,4,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,30-15,3-1,NaN,1,4761000,,,104,,1,Ad,Player1,Far,1.0,T,-37.021954,-221.222736,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,30-15,3-1,NaN,,4761000,,,104,,2,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,30-15,3-1,NaN,,4764000,,,104,,3,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,30-15,3-1,NaN,,4765000,,,104,,4,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,30-15,3-1,NaN,,4767000,,,104,,5,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,30-15,3-1,NaN,,4768000,,,104,,6,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,30-15,3-1,NaN,,4769000,,,104,,7,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
535,30-15,3-1,NaN,,4771000,1,4771000,104,,8,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536,40-15,3-1,NaN,1,4798000,,,105,,1,Deuce,Player1,Far,0.0,Body,68.006830,219.287746,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537,40-15,3-1,NaN,1,4809000,,,105,,1,Deuce,Player1,Far,NaN,,NaN,NaN,1.0,Body,60.133246,-142.828325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,40-15,3-1,NaN,,4811000,,,105,,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,40-15,3-1,NaN,,4812000,1,4812000,105,,3,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,40-30,3-1,NaN,1,4857000,,,106,,1,Ad,Player1,Far,1.0,T,-30.609345,-168.266251,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,40-30,3-1,NaN,,4858000,,,106,,2,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,40-30,3-1,NaN,,4859000,,,106,,3,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
543,40-30,3-1,NaN,,4861000,,,106,,4,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
shot_data[shot_data['isAce'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
462,15-30,1-1,NaN,1,4126000,1,4126000,91,,1,Ad,Player1,Near,0.0,Body,100.345505,-29.805616,NaN,,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### shotContactX and shotContactY Columns

In [48]:
# Functions to transform the swingvision coordinates
def transf_x_coord_sv_to_shot(sv_col) :
    return sv_col * 38.2764654418
def transf_y_coord_sv_to_shot(sv_col) :
    return (sv_col - 11.8872) * 38.2764654418

# want to convert swingvision coordinates into our own
shot_data['shotContactX'] = transf_x_coord_sv_to_shot(swing_data['Hit (x)'])
shot_data['shotContactY'] = transf_y_coord_sv_to_shot(swing_data['Hit (y)'])

### shotDirection column

In [49]:
# down the line --> switches btwn deuce and ad
# crosscourt --> remains on same side
shot_data['shotDirection'] = np.where((shot_data.shotContactX * shot_data.shotLocationX > 0) & (shot_data.shotInRally != 1), "Down the Line", 
    np.where(shot_data.shotInRally != 1, 'Crosscourt', ''))

### shotFhBh Column

In [50]:
def classify_shot(stroke):
    if stroke == 'FH Volley':
        return 'Forehand'
    elif stroke == 'BH Volley':
        return 'Backhand'
    elif stroke == 'Forehand':
        return 'Forehand'
    elif stroke == 'Backhand':
        return 'Backhand'
    elif stroke == 'Overhead':
        return 'Forehand'
    else:
        return ''

# Applying the function to the DataFrame
shot_data['shotFhBh'] = swing_data['Stroke'].apply(classify_shot)

### isSlice, isTopspin, isFlat, isKick Columns

In [51]:
shot_data['isSlice'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Slice' else '')
shot_data['isTopspin'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Topspin' else '') # added these metrics
shot_data['isFlat'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Flat' else '') # added these metrics
shot_data['isKick'] = swing_data['Spin'].apply(lambda x: '1' if x == 'Kick' else '') # added these metrics

### isVolley Column
- Volleys are inaccurate

In [52]:
shot_data['isVolley'] = swing_data['Stroke'].apply(lambda x: 1 if x in ['FH Volley', 'BH Volley'] else '') # need to classify shotFhBh when doing isVolley

In [53]:
shot_data[shot_data['isVolley'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
7,0-0,0-0,NaN,,11000,,,1,,8,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-81.201761,382.480260,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
10,0-0,0-0,NaN,,14000,1,14000,1,,11,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-34.154549,-113.881594,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
32,30-30,0-0,NaN,,161000,1,161000,5,,5,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,67.970888,-185.494718,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
72,15-15,2-0,NaN,,540000,1,540000,14,,5,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,152.156491,155.988424,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
77,15-30,2-0,NaN,,568000,1,568000,15,,5,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-5.082579,110.927723,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
91,0-0,2-1,NaN,,749000,1,749000,18,,5,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-10.579692,161.605342,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
139,15-30,4-1,NaN,,1299000,,,31,,5,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-84.472332,-148.262855,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
147,30-40,4-1,NaN,,1379000,,,33,1,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,93.536581,-136.082710,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
203,40-30,4-3,NaN,,1852000,,,44,,9,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,104.169171,307.056600,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
242,30-40,5-3,NaN,,2102000,,,50,1,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-57.485127,-213.968045,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
261,40-40,5-3,NaN,,2168000,1,2168000,51,1,17,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-22.817137,-357.442361,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
291,0-0,5-5,NaN,,2504000,1,2504000,57,,5,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,145.362265,311.605796,Crosscourt,Backhand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
486,0-15,2-1,NaN,,4428000,,,96,,5,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-13.395576,-334.447392,Crosscourt,Forehand,,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,

In [54]:
clean_df[clean_df['isVolley'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
7,0-0,0-0,0-0,NaN,19945,NaN,NaN,NaN,NaN,8,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-35.0,390.0,Crosscourt,Forehand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,-265.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0-0,0-0,0-0,NaN,23537,1.0,NaN,NaN,NaN,11,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-19.0,-211.0,Down the Line,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,-61.0,269.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,15-15,2-0,0-0,NaN,548616,1.0,NaN,NaN,NaN,5,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,154.0,61.0,Down the Line,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,66.0,0.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,15-30,2-0,0-0,NaN,576541,1.0,577291.0,NaN,NaN,5,Deuce,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.0,37.0,Down the Line,Forehand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.0,-258.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,0-0,2-1,0-0,NaN,758253,1.0,NaN,NaN,NaN,5,Ad,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,45.0,Crosscourt,Forehand,NaN,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,-118.0,-53.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,15-30,4-1,0-0,NaN,1307529,NaN,NaN,NaN,NaN,5,Ad,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-83.0,-176.0,Crosscourt,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,362.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,30-40,4-1,0-0,NaN,1387220,1.0,NaN,NaN,NaN,5,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,-99.0,Down the Line,Forehand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,234.0,-45.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,40-30,4-3,0-0,NaN,1859870,NaN,NaN,NaN,NaN,9,Ad,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,108.0,Down the Line,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,82.0,-324.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,30-40,5-3,0-0,NaN,2108701,NaN,NaN,NaN,NaN,4,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.0,494.0,Crosscourt,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,-83.0,-287.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,0-15,2-1,1-0,NaN,4434787,NaN,NaN,NaN,NaN,4,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172.0,502.0,Crosscourt,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,-23.0,-262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
443,0-15,2-1,1-0,NaN,4437976,NaN,NaN,NaN,NaN,6,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-31.0,539.0,Down the Line,Forehand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-17.0,-145.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,40-15,3-1,1-0,NaN,4820329,1.0,NaN,NaN,NaN,3,Deuce,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-129.0,486.0,Down the Line,Forehand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-305.0,170.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,15-15,5-2,1-0,NaN,5839610,1.0,NaN,NaN,NaN,5,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-27.0,-139.0,Down the Line,Forehand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,-147.0,325.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680,30-0,5-3,1-0,NaN,6059755,1.0,NaN,NaN,NaN,3,Ad,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,171.0,Crosscourt,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-283.0,-544.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### isOverhead Column
- Overheads are inaccurate

In [55]:
shot_data['isOverhead'] = swing_data['Stroke'].apply(lambda x: 1 if x == 'Overhead' else '')

In [56]:
shot_data[shot_data['isOverhead'] == 1]

Empty DataFrame
Columns: [pointScore, gameScore, setScore, isPointStart, pointStartTime, isPointEnd, pointEndTime, pointNumber, isBreakPoint, shotInRally, side, serverName, serverFarNear, firstServeIn, firstServeZone, firstServeXCoord, firstServeYCoord, secondServeIn, secondServeZone, secondServeXCoord, secondServeYCoord, isAce, shotContactX, shotContactY, shotDirection, shotFhBh, isSlice, isVolley, isOverhead, isApproach, isDropshot, isExcitingPoint, atNetPlayer1, atNetPlayer2, isLob, shotLocationX, shotLocationY, isWinner, isErrorWideR, isErrorWideL, isErrorNet, isErrorLong, clientTeam, Date, Division, Event, lineupPosition, matchDetails, matchVenue, opponentTeam, player1Name, player2Name, player1Hand, player2Hand, Round, Surface, Notes, isTopspin, isFlat, isKick]
Index: []

In [57]:
clean_df[clean_df['isOverhead'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
278,40-15,5-5,0-0,NaN,2636080,1.0,NaN,NaN,NaN,5,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,220.0,Down the Line,Forehand,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,80.0,-217.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,30-30,5-2,1-0,NaN,5921523,1.0,NaN,NaN,NaN,3,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.0,-56.0,Down the Line,Forehand,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,-72.0,173.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### isApproach Column

### isDropshot Column

### isExcitingPoint

### atNetPlayer1 and atNetPlayer2 Columns

### isLob Column

### shotLocationX and shotLocationY Columns

In [58]:
# Functions to transform the swingvision coordinates
def transf_x_loc(stroke, sv_col):
    if stroke != 'first_serve' and stroke != 'second_serve':
        return sv_col * 38.2764654418
    return np.nan
    
def transf_y_loc(stroke, sv_col):
    if stroke != 'first_serve' and stroke != 'second_serve':
        return (sv_col - 11.8872) * 38.2764654418
    return np.nan

# want to convert swingvision coordinates into our own
shot_data['shotLocationX'] = swing_data.apply(lambda x: transf_x_loc(x['Type'], x['Bounce (x)']), axis=1)
shot_data['shotLocationY'] = swing_data.apply(lambda x: transf_y_loc(x['Type'], x['Bounce (y)']), axis=1)

### isWinner Column

In [59]:
shot_data.isWinner = np.where((shot_data.isPointEnd == 1) & (shot_data.secondServeIn != '0') &
                              (swing_data.Result == 'In'), 1, np.nan)

In [60]:
shot_data[shot_data['isWinner'] == 1]
# shot_data[330:345]
shot_data[shot_data['pointNumber'] == 10]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
49,30-0,1-0,NaN,1,382000,,,10,,1,Deuce,Player1,Near,0.0,Body,-90.386122,395.858268,NaN,,NaN,NaN,NaN,37.580944,-452.119505,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
50,30-0,1-0,NaN,1,397000,,,10,,1,Deuce,Player1,Near,NaN,,NaN,NaN,1.0,Body,-64.241803,182.212741,NaN,27.026936,-450.722031,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
51,30-0,1-0,NaN,,398000,,,10,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-110.922824,534.436871,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,69.755337,-246.123759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
52,30-0,1-0,NaN,,399000,,,10,,3,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,121.947709,-489.812675,Crosscourt,Forehand,1,,,NaN,NaN,NaN,NaN,NaN,NaN,70.207841,296.331496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
53,30-0,1-0,NaN,,401000,,,10,,4,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,94.056912,322.778850,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,114.504697,-456.365092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
54,30-0,1-0,NaN,,402000,1,402000,10,,5,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,116.107065,-496.417011,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-104.138780,351.028106,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,

In [61]:
clean_df[clean_df['isWinner'] == 1]
clean_df[clean_df['pointNumber'] == 10]
clean_df[40:60]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
40,0-0,1-0,0-0,NaN,307425,NaN,NaN,NaN,NaN,2,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-163.0,448.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.0,-310.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,0-0,1-0,0-0,NaN,308720,NaN,NaN,NaN,NaN,3,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.0,-507.0,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,261.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,0-0,1-0,0-0,NaN,310100,1.0,NaN,NaN,NaN,4,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-51.0,472.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,15-0,1-0,0-0,1.0,327879,NaN,NaN,NaN,NaN,1,Ad,Player1,Near,0.0,T,19.0,381.0,1.0,Wide,107.0,240.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,15-0,1-0,0-0,NaN,358063,1.0,NaN,NaN,NaN,2,Ad,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,480.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,30-0,1-0,0-0,1.0,387723,NaN,NaN,NaN,NaN,1,Deuce,Player1,Near,0.0,Body,-56.0,323.0,1.0,Body,-64.0,197.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,30-0,1-0,0-0,NaN,405938,NaN,NaN,NaN,NaN,2,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-64.0,467.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,-246.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,30-0,1-0,0-0,NaN,407099,NaN,NaN,NaN,NaN,3,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.0,-526.0,Down the Line,Forehand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,272.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,30-0,1-0,0-0,NaN,409367,1.0,414275.0,NaN,NaN,4,Ad,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123.0,293.0,Down the Line,Forehand,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,126.0,-502.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,40-0,1-0,0-0,1.0,440352,1.0,NaN,NaN,NaN,1,Ad,Player1,Near,1.0,Wide,109.0,243.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,0-0,2-0,0-0,1.0,469855,NaN,NaN,NaN,NaN,1,Deuce,Player2,Far,0.0,Body,50.0,-261.0,1.0,T,48.0,-210.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,0-0,2-0,0-0,NaN,483719,NaN,NaN,NaN,NaN,2,Deuce,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.0,-480.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-110.0,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,0-0,2-0,0-0,NaN,485316,1.0,NaN,NaN,NaN,3,Deuce,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-136.0,485.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176.0,-274.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,0-15,2-0,0-0,1.0,507449,NaN,NaN,NaN,NaN,1,Ad,Player2,Far,1.0,Body,-94.0,-234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,0-15,2-0,0-0,NaN,511924,NaN,NaN,NaN,NaN,2,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-131.0,-493.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-88.0,408.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,0-15,2-0,0-0,NaN,512399,NaN,NaN,NaN,NaN,3,Deuce,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-48.0,480.0,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-19.0,-258.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,0-15,2-0,0-0,NaN,513648,NaN,NaN,NaN,NaN,4,Deuce,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,-488.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.0,405.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,0-15,2-0,0-0,NaN,515910,NaN,NaN,NaN,NaN,5,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,472.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-134.0,-213.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,0-15,2-0,0-0,NaN,517131,NaN,NaN,NaN,NaN,6,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-235.0,-522.0,Crosscourt,Backhand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,0-15,2-0,0-0,NaN,518425,1.0,519800.0,NaN,NaN,7,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,442.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-96.0,-330.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### isErrorWideR

In [62]:
def wide_right_function(side, x, y, end):
    if (side == 'far' and x < -157.5 and y > -405 and y < 0 and end == 1) or (side == 'near' and x > 157.5 and y < 405 and y > 0 and end == 1):
        return 1
    return np.nan

# Assign 'isErrorWideR' using values from both 'swing_data' and 'shot_data'
shot_data['isErrorWideR'] = shot_data.apply(lambda x: wide_right_function(swing_data.loc[x.name, 'Hit Side'], 
                                                                x['shotLocationX'], x['shotLocationY'], x['isPointEnd']), axis=1)

### isErrorWideL

In [63]:
def wide_left_function(side, x, y, end):
    if (side == 'far' and x > 157.5 and y > -405 and y < 0 and end == 1) or (side == 'near' and x < -157.5 and y < 405 and y > 0 and end == 1):
        return 1
    return np.nan

# Assign 'isErrorWideR' using values from both 'swing_data' and 'shot_data'
shot_data['isErrorWideL'] = shot_data.apply(lambda x: wide_left_function(swing_data.loc[x.name, 'Hit Side'], 
                                                                x['shotLocationX'], x['shotLocationY'], x['isPointEnd']), axis=1)

### isErrorNet Column

In [64]:
shot_data.isErrorNet = np.where((swing_data.Result == 'Net'), 1, np.nan)

### isErrorLong Column

In [65]:
shot_data['isErrorLong'] = np.where((swing_data['Result'] == 'Out') & (shot_data['shotLocationY'].abs() > 455), 1, np.nan)

In [66]:
shot_data[shot_data['isErrorLong'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
53,30-0,1-0,NaN,,401000,,,10,,4,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,94.056912,322.778850,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,114.504697,-456.365092,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
133,0-30,4-1,NaN,,1264000,1,1264000,30,,2,Deuce,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-45.484230,461.262374,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,38.160947,-531.098742,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
160,15-15,4-2,NaN,,1483000,1,1483000,36,,6,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,119.421730,-488.511926,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-57.767186,467.206939,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
170,30-15,4-2,NaN,,1518000,,,37,,10,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,116.832519,-511.145642,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-92.541202,577.964561,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
294,15-0,5-5,NaN,,2532000,1,2532000,58,,2,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-80.337478,-444.966207,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-69.364840,523.843323,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
320,30-0,5-6,NaN,,2815000,,,64,,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,92.009312,-434.897583,Crosscourt,Backhand,1,,,NaN,NaN,NaN,NaN,NaN,NaN,-79.842257,519.986587,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
328,40-0,5-6,NaN,,2854000,1,2854000,65,,2,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-177.931059,-513.061877,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,93.315918,489.398600,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
335,15-0,6-6,NaN,,2925000,,,67,,2,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-126.692000,-461.603111,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-71.256310,483.886100,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
366,0-0,0-0,NaN,,3185000,,,74,,4,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,189.732535,-515.317738,Crosscourt,Forehand,1,,,NaN,NaN,NaN,NaN,NaN,NaN,-83.379500,496.293493,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
395,15-40,0-0,NaN,,3582000,1,3582000,78,1,10,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,51.270254,-515.490404,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-94.432940,563.108164,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
397,30-40,0-0,NaN,,3610000,1,3610000,79,1,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,205.663506,-493.806862,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-72.607393,691.161428,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
400,40-40,0-0,NaN,,3653000,1,3653000,80,1,2,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-82.525361,-524.863430,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-100.119751,674.547337,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
417,0-15,0-1,NaN,,3773000,1,3773000,82,,14,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-22.578177,-425.009050,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-87.513971,495.820779,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
493,15-15,2-1,NaN,,4469000,1,4469000,97,,6,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,149.144783,523.537571,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-51.586991,-483.158809,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
587,15-0,4-1,NaN,,5114000,1,5114000,109,,18,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-32.365163,-476.843154,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,156.840458,595.655217,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
656,15-30,4-2,NaN,,5491000,,,117,,11,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-123.569330,-484.028182,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-1.061253,480.419516,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
664,15-40,4-2,NaN,,5548000,1,5548000,118,1,6,Ad,Player1,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,54.957655,551.335165,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-98.096112,-460.305424,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
682,0-0,5-2,NaN,,5747000,1,5747000,121,,2,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-167.235428,541.143099,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,201.167361,-463.001848,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
736,30-0,5-3,NaN,,6051000,1,6051000,129,,3,Ad,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,42.579161,399.857010,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-160.216519,-489.722266,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
747,30-30,5-3,NaN,,6137000,1,6137000,131,,2,Deuce,Player1,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,48.793039,-482.407404,Crosscourt,Backhand,1,,,NaN,NaN,NaN,NaN,NaN,NaN,-158.902909,496.832923,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,

In [67]:
shot_data[160:175]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
160,15-15,4-2,NaN,,1483000,1,1483000,36,,6,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,119.421730,-488.511926,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-57.767186,467.206939,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
161,30-15,4-2,NaN,1,1506000,,,37,,1,Ad,Player2,Far,1.0,Wide,-140.920511,-173.561456,NaN,,NaN,NaN,NaN,30.166027,500.731649,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
162,30-15,4-2,NaN,,1507000,,,37,,2,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-191.086871,-500.997211,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-49.959170,455.000038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
163,30-15,4-2,NaN,,1508000,,,37,,3,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-24.335182,538.800771,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-103.070139,-364.349923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
164,30-15,4-2,NaN,,1510000,,,37,,4,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-124.310898,-525.073299,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,46.116825,454.508913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
165,30-15,4-2,NaN,,1511000,,,37,,5,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,79.692405,539.011177,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-91.130599,-409.899645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
166,30-15,4-2,NaN,,1513000,,,37,,6,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-130.244401,-519.548360,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,109.388320,450.928532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
167,30-15,4-2,NaN,,1514000,,,37,,7,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,139.766514,507.456862,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-56.881392,-202.994144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
168,30-15,4-2,NaN,,1515000,,,37,,8,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-115.984503,-475.993876,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,4.642667,239.010460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
169,30-15,4-2,NaN,,1517000,,,37,,9,Ad,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,98.361100,515.859159,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,99.510351,-308.613419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
170,30-15,4-2,NaN,,1518000,,,37,,10,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,116.832519,-511.145642,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-92.541202,577.964561,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
171,30-15,4-2,NaN,,1519000,1,1519000,37,,11,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-75.359700,547.191317,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,153.169056,-297.570046,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
172,40-15,4-2,NaN,1,1544000,,,38,,1,Deuce,Player2,Far,1.0,Wide,143.772146,-196.763462,NaN,,NaN,NaN,NaN,-63.649207,433.760963,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
173,40-15,4-2,NaN,,1545000,,,38,,2,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,197.638845,-471.416164,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-177.710816,355.290497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
174,40-15,4-2,NaN,,1547000,1,1547000,38,,3,Deuce,Player2,Far,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-210.536981,456.000509,Crosscourt,Forehand,1,,,NaN,NaN,NaN,NaN,NaN,NaN,-141.892006,30.835406,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,

In [68]:
clean_df[clean_df['isErrorLong'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
48,30-0,1-0,0-0,NaN,409367,1.0,414275.0,NaN,NaN,4,Ad,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123.0,293.0,Down the Line,Forehand,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,126.0,-502.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,0-30,4-1,0-0,NaN,1272462,1.0,NaN,NaN,NaN,2,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-126.0,442.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,-613.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,15-15,4-2,0-0,NaN,1492378,1.0,NaN,NaN,NaN,6,Deuce,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.0,-473.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-100.0,513.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,30-15,4-2,0-0,NaN,1526407,1.0,NaN,NaN,NaN,14,Deuce,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,-580.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-83.0,477.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,15-0,5-5,0-0,NaN,2540537,1.0,NaN,NaN,NaN,2,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-91.0,-401.0,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-86.0,489.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,40-0,5-6,0-0,NaN,2862722,1.0,NaN,NaN,NaN,2,Ad,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-200.0,-337.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0,486.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,1-0,6-6,0-0,NaN,2933205,1.0,NaN,NaN,NaN,2,Ad,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-111.0,-475.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-71.0,467.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,0-3,6-6,0-0,NaN,3008600,1.0,NaN,NaN,NaN,8,Deuce,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-47.0,451.0,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,-180.0,-467.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,0-15,0-0,1-0,NaN,3513110,1.0,NaN,NaN,NaN,5,Deuce,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.0,397.0,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-120.0,-488.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,0-40,0-0,1-0,NaN,3590106,1.0,NaN,NaN,NaN,10,Deuce,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,-519.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-64.0,519.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,15-40,0-0,1-0,NaN,3618133,1.0,NaN,NaN,NaN,2,Deuce,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218.0,-457.0,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.0,521.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421,15-30,1-1,1-0,NaN,4158705,1.0,NaN,NaN,NaN,5,Deuce,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,-503.0,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,505.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,0-30,2-1,1-0,NaN,4477071,1.0,NaN,NaN,NaN,6,Ad,Player2,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,483.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-33.0,-480.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537,15-0,4-1,1-0,NaN,5122209,1.0,NaN,NaN,NaN,18,Ad,Player2,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-30.0,-538.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130.0,517.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,30-15,4-2,1-0,NaN,5500120,1.0,NaN,NaN,NaN,11,Ad,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-107.0,-514.0,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-22.0,504.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,30-30,4-2,1-0,NaN,5556178,1.0,NaN,NaN,NaN,6,Ad,Player1,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,496.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-72.0,-533.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680,30-0,5-3,1-0,NaN,6059755,1.0,NaN,NaN,NaN,3,Ad,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,171.0,Crosscourt,Backhand,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-283.0,-544.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,30-30,5-3,1-0,NaN,6145675,1.0,NaN,NaN,NaN,2,Deuce,Player1,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,-496.0,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,-160.0,474.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Group First Serve and Second Serve Columns

In [69]:
shot_data

    pointScore gameScore setScore isPointStart pointStartTime isPointEnd  \
0          0-0       0-0      NaN            1              0
1          0-0       0-0      NaN                        2000
2          0-0       0-0      NaN                        3000
3          0-0       0-0      NaN                        5000
4          0-0       0-0      NaN                        7000
5          0-0       0-0      NaN                        8000
6          0-0       0-0      NaN                       10000
7          0-0       0-0      NaN                       11000
8          0-0       0-0      NaN                       12000
9          0-0       0-0      NaN                       14000
10         0-0       0-0      NaN                       14000          1
11        15-0       0-0      NaN            1          46000
12        15-0       0-0      NaN                       47000
13        15-0       0-0      NaN                       48000
14        15-0       0-0      NaN                       49000
15        15-0       0-0      NaN                       52000          1
16       15-15       0-0      NaN            1          73000
17       15-15       0-0      NaN            1          87000
18       15-15       0-0      NaN                       88000
19       15-15       0-0      NaN                       90000
20       15-15       0-0      NaN                       91000
21       15-15       0-0      NaN                       92000
22       15-15       0-0      NaN                       94000
23       15-15       0-0      NaN                       95000
24       15-15       0-0      NaN                       96000
25       15-15       0-0      NaN                       98000          1
26       30-15       0-0      NaN            1         124000
27       30-15       0-0      NaN            1         135000          1
28       30-30       0-0      NaN            1         156000
29       30-30       0-0      NaN                      157000
30       30-30       0-0      NaN                      159000
31       30-30       0-0      NaN                      160000
32       30-30       0-0      NaN                      161000          1
33       30-40       0-0      NaN            1         184000
34       30-40       0-0      NaN                      185000          1
35       40-40       0-0      NaN            1         206000
36       40-40       0-0      NaN                      207000
37       40-40       0-0      NaN                      209000
38       40-40       0-0      NaN                      210000
39       40-40       0-0      NaN                      211000
40       40-40       0-0      NaN                      213000
41       40-40       0-0      NaN                      214000          1
42         0-0       1-0      NaN            1         298000
43         0-0       1-0      NaN                      299000
44         0-0       1-0      NaN                      300000
45         0-0       1-0      NaN                      302000          1
46        15-0       1-0      NaN            1         326000
47        15-0       1-0      NaN            1         349000
48        15-0       1-0      NaN                      350000          1
49        30-0       1-0      NaN            1         382000
50        30-0       1-0      NaN            1         397000
51        30-0       1-0      NaN                      398000
52        30-0       1-0      NaN                      399000
53        30-0       1-0      NaN                      401000
54        30-0       1-0      NaN                      402000          1
55        40-0       1-0      NaN            1         434000
56        40-0       1-0      NaN                      435000          1
57         0-0       2-0      NaN            1         463000
58         0-0       2-0      NaN            1         474000
59         0-0       2-0      NaN                      475000
60         0-0       2-0      NaN                      477000          1
61        0-15       2-0      NaN            1         502000
62        0-15       2-0      NaN                      503000
63        0-15       2-0      NaN                      504000
64        0-15       2-0      NaN                      505000
65        0-15       2-0      NaN                      507000
66        0-15       2-0      NaN                      508000
67        0-15       2-0      NaN                      510000          1
68       15-15       2-0      NaN            1         534000
69       15-15       2-0      NaN                      535000
70       15-15       2-0      NaN                      538000
71       15-15       2-0      NaN                      539000
72       15-15       2-0      NaN                      540000          1
73       15-30       2-0      NaN            1         563000
74       15-30       2-0      NaN                      564000
75       15-30       2-0      NaN                      566000
76       15-30       2-0      NaN                      567000
77       15-30       2-0      NaN                      568000          1
78       30-30       2-0      NaN            1         596000
79       30-30       2-0      NaN            1         605000
80       30-30       2-0      NaN                      606000
81       30-30       2-0      NaN                      607000
82       30-30       2-0      NaN                      608000
83       30-30       2-0      NaN                      610000
84       30-30       2-0      NaN                      611000          1
85       40-30       2-0      NaN            1         636000
86       40-30       2-0      NaN                      637000          1
87         0-0       2-1      NaN            1         745000
88         0-0       2-1      NaN                      746000
89         0-0       2-1      NaN                      747000
90         0-0       2-1      NaN                      749000
91         0-0       2-1      NaN                      749000          1
92        15-0       2-1      NaN            1         772000
93        15-0       2-1      NaN                      773000          1
94        30-0       2-1      NaN            1         795000
95        30-0       2-1      NaN                      796000          1
96        40-0       2-1      NaN            1         817000
97        40-0       2-1      NaN                      818000
98        40-0       2-1      NaN                      820000          1
99         0-0       3-1      NaN            1         849000
100        0-0       3-1      NaN                      850000          1
101       15-0       3-1      NaN            1         873000
102       15-0       3-1      NaN                      874000
103       15-0       3-1      NaN                      876000          1
104      15-15       3-1      NaN            1         897000
105      15-15       3-1      NaN            1         914000
106      15-15       3-1      NaN                      915000
107      15-15       3-1      NaN                      917000
108      15-15       3-1      NaN                      918000
109      15-15       3-1      NaN                      919000
110      15-15       3-1      NaN                      921000
111      15-15       3-1      NaN                      922000
112      15-15       3-1      NaN                      923000
113      15-15       3-1      NaN                      925000
114      15-15       3-1      NaN                      926000
115      15-15       3-1      NaN                      929000          1
116      30-15       3-1      NaN            1         955000
117      30-15       3-1      NaN                      956000
118      30-15       3-1      NaN                      958000          1
119      30-30       3-1      NaN            1         983000
120      30-30       3-1      NaN            1         993000          1
121      30-40       3-1      NaN            1        1015000
122      30-40       3-1      NaN            1        1028000
123      30-40       3-1      NaN                     1029000          1
124        0-0       4-1      NaN            1        1137000
125        0-0       4-1      NaN            1        1165000
126        0-0       4-1      NaN            1        1181000          1
127       0-15       4-1      NaN            1        1206000
128       0-15       4-1      NaN            1        1219000
129       0-15       4-1      NaN                     1220000
130       0-15       4-1      NaN                     1221000          1
131       0-30       4-1      NaN            1        1247000
132       0-30       4-1      NaN            1        1263000
133       0-30       4-1      NaN                     1264000          1
134      15-30       4-1      NaN            1        1283000
135      15-30       4-1      NaN            1        1294000
136      15-30       4-1      NaN                     1295000
137      15-30       4-1      NaN                     1296000
138      15-30       4-1      NaN                     1298000
139      15-30       4-1      NaN                     1299000
140      15-30       4-1      NaN                     1300000          1
141      30-30       4-1      NaN            1        1326000
142      30-30       4-1      NaN            1        1343000          1
143      30-40       4-1      NaN            1        1374000
144      30-40       4-1      NaN                     1375000
145      30-40       4-1      NaN                     1376000
146      30-40       4-1      NaN                     1378000
147      30-40       4-1      NaN                     1379000
148      30-40       4-1      NaN                     1381000          1
149        0-0       4-2      NaN            1        1415000
150        0-0       4-2      NaN            1        1430000          1
151       0-15       4-2      NaN            1        1449000
152       0-15       4-2      NaN                     1450000
153       0-15       4-2      NaN                     1451000
154       0-15       4-2      NaN                     1453000          1
155      15-15       4-2      NaN            1        1476000
156      15-15       4-2      NaN                     1477000
157      15-15       4-2      NaN                     1479000
158      15-15       4-2      NaN                     1480000
159      15-15       4-2      NaN                     1482000
160      15-15       4-2      NaN                     1483000          1
161      30-15       4-2      NaN            1        1506000
162      30-15       4-2      NaN                     1507000
163      30-15       4-2      NaN                     1508000
164      30-15       4-2      NaN                     1510000
165      30-15       4-2      NaN                     1511000
166      30-15       4-2      NaN                     1513000
167      30-15       4-2      NaN                     1514000
168      30-15       4-2      NaN                     1515000
169      30-15       4-2      NaN                     1517000
170      30-15       4-2      NaN                     1518000
171      30-15       4-2      NaN                     1519000          1
172      40-15       4-2      NaN            1        1544000
173      40-15       4-2      NaN                     1545000
174      40-15       4-2      NaN                     1547000          1
175        0-0       4-3      NaN            1        1650000
176        0-0       4-3      NaN                     1651000          1
177       15-0       4-3      NaN            1        1671000
178       15-0       4-3      NaN                     1672000
179       15-0       4-3      NaN                     1673000
180       15-0       4-3      NaN                     1675000
181       15-0       4-3      NaN                     1676000
182       15-0       4-3      NaN                     1678000
183       15-0       4-3      NaN                     1679000
184       15-0       4-3      NaN                     1680000          1
185       30-0       4-3      NaN            1        1710000
186       30-0       4-3      NaN            1        1720000
187       30-0       4-3      NaN                     1721000          1
188      30-15       4-3      NaN            1        1753000
189      30-15       4-3      NaN            1        1763000
190      30-15       4-3      NaN                     1764000          1
191      30-30       4-3      NaN            1        1808000
192      30-30       4-3      NaN                     1809000
193      30-30       4-3      NaN                     1811000
194      30-30       4-3      NaN                     1812000          1
195      40-30       4-3      NaN            1        1840000
196      40-30       4-3      NaN                     1841000
197      40-30       4-3      NaN                     1843000
198      40-30       4-3      NaN                     1844000
199      40-30       4-3      NaN                     1846000
200      40-30       4-3      NaN                     1848000
201      40-30       4-3      NaN                     1849000
202      40-30       4-3      NaN                     1850000
203      40-30       4-3      NaN                     1852000
204      40-30       4-3      NaN                     1853000          1
205        0-0       5-3      NaN            1        1895000
206        0-0       5-3      NaN            1        1910000
207        0-0       5-3      NaN                     1911000
208        0-0       5-3      NaN                     1912000
209        0-0       5-3      NaN                     1913000
210        0-0       5-3      NaN                     1915000
211        0-0       5-3      NaN                     1916000
212        0-0       5-3      NaN                     1918000
213        0-0       5-3      NaN                     1919000
214        0-0       5-3      NaN                     1921000
215        0-0       5-3      NaN                     1922000
216        0-0       5-3      NaN                     1924000
217        0-0       5-3      NaN                     1925000          1
218       15-0       5-3      NaN            1        1954000
219       15-0       5-3      NaN            1        1964000
220       15-0       5-3      NaN                     1966000
221       15-0       5-3      NaN                     1967000          1
222      15-15       5-3      NaN            1        1998000
223      15-15       5-3      NaN                     1999000
224      15-15       5-3      NaN                     2001000          1
225      15-30       5-3      NaN            1        2031000
226      15-30       5-3      NaN                     2032000
227      15-30       5-3      NaN                     2033000
228      15-30       5-3      NaN                     2035000
229      15-30       5-3      NaN                     2036000
230      15-30       5-3      NaN                     2037000
231      15-30       5-3      NaN                     2039000          1
232      15-40       5-3      NaN            1        2066000
233      15-40       5-3      NaN                     2067000
234      15-40       5-3      NaN                     2068000
235      15-40       5-3      NaN                     2070000
236      15-40       5-3      NaN                     2071000
237      15-40       5-3      NaN                     2073000          1
238      30-40       5-3      NaN            1        2096000
239      30-40       5-3      NaN                     2097000
240      30-40       5-3      NaN                     2099000
241      30-40       5-3      NaN                     2100000
242      30-40       5-3      NaN                     2102000
243      30-40       5-3      NaN                     2103000          1
244      40-40       5-3      NaN            1        2132000
245      40-40       5-3      NaN            1        2143000
246      40-40       5-3      NaN                     2144000
247      40-40       5-3      NaN                     2146000
248      40-40       5-3      NaN                     2147000
249      40-40       5-3      NaN                     2149000
250      40-40       5-3      NaN                     2150000
251      40-40       5-3      NaN                     2151000
252      40-40       5-3      NaN                     2153000
253      40-40       5-3      NaN                     2154000
254      40-40       5-3      NaN                     2156000
255      40-40       5-3      NaN                     2158000
256      40-40       5-3      NaN                     2160000
257      40-40       5-3      NaN                     2161000
258      40-40       5-3      NaN                     2163000
259      40-40       5-3      NaN                     2165000
260      40-40       5-3      NaN                     2166000
261      40-40       5-3      NaN                     2168000          1
262        0-0       5-4      NaN            1        2286000
263        0-0       5-4      NaN                     2288000          1
264       0-15       5-4      NaN            1        2310000
265       0-15       5-4      NaN                     2311000          1
266      15-15       5-4      NaN            1        2340000
267      15-15       5-4      NaN                     2341000
268      15-15       5-4      NaN                     2343000
269      15-15       5-4      NaN                     2344000          1
270      15-30       5-4      NaN            1        2375000
271      15-30       5-4      NaN            1        2391000
272      15-30       5-4      NaN                     2392000
273      15-30       5-4      NaN                     2394000
274      15-30       5-4      NaN                     2395000
275      15-30       5-4      NaN                     2397000
276      15-30       5-4      NaN                     2400000
277      15-30       5-4      NaN                     2401000
278      15-30       5-4      NaN                     2402000          1
279      15-40       5-4      NaN            1        2430000
280      15-40       5-4      NaN                     2431000
281      15-40       5-4      NaN                     2434000
282      15-40       5-4      NaN                     2436000
283      15-40       5-4      NaN                     2437000
284      15-40       5-4      NaN                     2439000
285      15-40       5-4      NaN                     2440000          1
286        0-0       5-5      NaN            1        2481000
287        0-0       5-5      NaN            1        2490000
288        0-0       5-5      NaN                     2491000
289        0-0       5-5      NaN                     2493000
290        0-0       5-5      NaN                     2494000
291        0-0       5-5      NaN                     2504000          1
292       15-0       5-5      NaN            1        2521000
293       15-0       5-5      NaN            1        2531000
294       15-0       5-5      NaN                     2532000          1
295       30-0       5-5      NaN            1        2557000
296       30-0       5-5      NaN                     2558000
297       30-0       5-5      NaN                     2560000
298       30-0       5-5      NaN                     2561000
299       30-0       5-5      NaN                     2562000          1
300      30-15       5-5      NaN            1        2587000
301      30-15       5-5      NaN            1        2598000
302      30-15       5-5      NaN                     2599000          1
303      40-15       5-5      NaN            1        2622000
304      40-15       5-5      NaN                     2623000
305      40-15       5-5      NaN                     2625000
306      40-15       5-5      NaN                     2626000          1
307        0-0       5-6      NaN            1        2737000
308        0-0       5-6      NaN                     2738000
309        0-0       5-6      NaN                     2739000          1

In [74]:
test_df = shot_data[shot_data['pointNumber'] == 3]
test_df

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick
16,15-15,0-0,NaN,1,73000,,,3,,1,Deuce,Player2,Near,0.0,Body,-59.159072,-17.149847,NaN,,NaN,NaN,NaN,80.172315,-454.070265,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
17,15-15,0-0,NaN,1,87000,,,3,,1,Deuce,Player2,Near,NaN,,NaN,NaN,1.0,Wide,-127.31005,239.01046,NaN,105.082869,-441.648748,,,1,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,
18,15-15,0-0,NaN,,88000,,,3,,2,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-198.797359,520.182486,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,91.884110,-374.479063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
19,15-15,0-0,NaN,,90000,,,3,,3,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,107.281009,-471.906332,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-106.723513,327.329003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,
20,15-15,0-0,NaN,,91000,,,3,,4,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-146.934432,529.462500,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,62.014534,-384.851947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
21,15-15,0-0,NaN,,92000,,,3,,5,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,70.806064,-514.361822,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,42.006009,454.386849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
22,15-15,0-0,NaN,,94000,,,3,,6,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,36.830840,567.529440,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-73.129637,-336.280720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
23,15-15,0-0,NaN,,95000,,,3,,7,Ad,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-82.558815,-498.427597,Crosscourt,Backhand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-57.436210,431.491475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
24,15-15,0-0,NaN,,96000,,,3,,8,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,-49.005244,553.955304,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,106.826629,-280.592328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,,
25,15-15,0-0,NaN,,98000,1,98000,3,,9,Deuce,Player2,Near,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,119.481939,-508.392416,Crosscourt,Forehand,,,,NaN,NaN,NaN,NaN,NaN,NaN,-125.936385,294.573573,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1,

In [81]:
# All columns
default_cols = ['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick']

# Assign all columns to have value be taken from the first serve row
agg_dict = {col: 'first' for col in default_cols}

# Reassign select columns to have value be taken form the second serve row
agg_dict.update({'isPointEnd': 'last', 
                 'pointEndTime': 'last', 
                 'secondServeIn' : 'last',
                 'secondServeZone' : 'last',
                 'secondServeXCoord' : 'last', 
                 'secondServeYCoord' : 'last',
                 'isAce' : 'last', 
                 'shotContactX' : 'last', 
                 'shotContactY' : 'last',
                 'isWinner' : 'last',
                 'isErrorWideR' : 'last',
                 'isErrorWideL' : 'last', 
                 'isErrorNet' : 'last',
                 'isErrorLong' : 'last'
                })

# Group by isPointStart and pointNumber
new_df = test_df.groupby(['isPointStart', 'pointNumber'], as_index=False).agg(agg_dict).reset_index(drop=True)

# Identify the ungrouped rows (rows that can't be grouped)
ungrouped_rows = test_df[~test_df['shotInRally'].isin(new_df['shotInRally'])]
ungrouped_rows

test_df['shotInRally'].isin(new_df['shotInRally'])
                            
# # Concatenate grouped and ungrouped rows
# final_df = pd.concat([new_df, ungrouped_rows]).reset_index(drop=True)

# # Sort by pointNumber and shotInRally in ascending order
# final_df_sorted = final_df.sort_values(by=['pointNumber', 'shotInRally']).reset_index(drop=True)
# final_df_sorted

16     True
17     True
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
Name: shotInRally, dtype: bool

In [ ]:
for i in shot_data['pointNumber'].unique().tolist():

    current_point = shot_data[shot_data['pointNumber'] == i]
    serves = current_point[current_point['shotInRally'] == 1]
    serves = serves.groupby(['isPointStart', 'pointNumber'], as_index=False).agg(agg_dict).reset_index(drop=True)
    
    # Remove the serve rows from the current_point DataFrame
    current_point_no_serves = current_point[current_point['shotInRally'] != 1]
    
    # Concatenate the serves at the top of current_point
    updated_point = pd.concat([serves, current_point_no_serves]).reset_index(drop=True)

In [ ]:
# new_shot_data = shot_data.groupby(['isPointStart', 'pointNumber'], as_index=True).agg(agg_dict).reset_index(drop=True)
# new_shot_data

In [ ]:
shot_data

### Save as CSV

In [ ]:
# if want to drop swingvision coords, drops all columns after 'Notes'
# shot_data = shot_data.loc[:, :'Notes']

shot_data.to_csv('swing_vision.csv', index=False)

### Serving Columns
#### * need to revise code for determining serves in/out
- if want to hardcode it:
- far deuce serve: x [0, 157.5], y [-245, 0]
- near deuce serve: x [-157.5, 0], y [0, 245]
- far ad serve: x [-157.5, 0], y [-245, 0]
- near ad serve: x [0, 157.5], y [0, 245]

### Points

In [ ]:
# ad scoring?

ad_scoring = False

In [ ]:
# want to record the score every time a point ends
# points: server - returner
# games: ucla (player1) - opp
# sets: ucla (player1) - opp
points = np.zeros(2)
games = np.zeros(2)
sets = np.zeros(2)
pt_values = [0, 15, 30, 40]



shot_data.loc[0,"pointScore"] = f"{pt_values[int(points[0])]} - {pt_values[int(points[1])]}"
shot_data.loc[0,"gameScore"] = f"{games[0]} - {games[1]}"
shot_data.loc[0,"setScore"] = f"{sets[0]} - {sets[1]}"

shot_data["isBreakPoint"] = ''

error_cols = [x for x in shot_data.columns if "isError" in x]

for i in range(0, len(shot_data.pointScore) - 1):
    if shot_data.loc[i+1, "isPointStart"] == 1: # means we gotta update pts
        # determine point score by checking last shot
        if shot_data.loc[i, "isWinner"] == "1":
            # check if player 1 or 2 won pt
            pt_winner_player_num = (np.where(shot_data.loc[i, "Player"] == shot_data.loc[0,"player1Name"], '1', '2'))
        elif shot_data.loc[i, 'secondServeIn'] == "0": # double fault
            pt_winner_player_num = (np.where(shot_data.loc[i, "Player"] == shot_data.loc[0,"player1Name"], '2', '1'))
        elif any(shot_data.loc[i,error_cols] == "1"):
            # winner is the player who did NOT hit that shot
            pt_winner_player_num = (np.where(shot_data.loc[i, "Player"] == shot_data.loc[0,"player1Name"], '2', '1'))
        else:
            print("no pt recorded at row ", i)

        if shot_data.loc[i, "serverName"] is not None:
            didServerWinPt = shot_data.loc[i, "serverName"][-1] == pt_winner_player_num
        else:
            print(f"Server name is None at row {i}. Skipping this point.")
            continue  # Skip this point if server name is None
        
        if didServerWinPt:
            points[0] += 1
        else:
            points[1] += 1


        if ad_scoring: # checks if need to win by 2
            if any(points > 3) and abs(points[0] - points[1]) >= 2:
                game_winner = np.argmax(points)  # Find who won the game
                games[game_winner] += 1
                points = np.zeros(2)  # Reset point values
            if any(games > 5) and abs(games[0] - games[1]) >= 2:
                set_winner = np.argmax(games)  # Find who won the set
                sets[set_winner] += 1
                games = np.zeros(2)  # Reset game values   
        else:
            if points[1] == 3: # if the returner has 40 pts and can win the game
                shot_data.loc[i + 1, 'isBreakPoint'] = '1'
            if any(points > 3):
                game_winner = np.argmax(points)  # Find who won the game
                games[game_winner] += 1
                points = np.zeros(2)  # Reset point values
            if any(games > 5):
                set_winner = np.argmax(games)  # Find who won the set
                sets[set_winner] += 1
                games = np.zeros(2)  # Reset game values   

    # Update the scores in the shot_data DataFrame
    shot_data.loc[i+1,"pointScore"] = f"{pt_values[int(points[0])]} - {pt_values[int(points[1])]}"
    shot_data.loc[i+1,"gameScore"] = f"{int(games[0])} - {int(games[1])}"
    shot_data.loc[i+1,"setScore"] = f"{int(sets[0])} - {int(sets[1])}"


# Additional comments for further updates:
# - Tiebreak scenarios are not yet handled and need to be accounted for in future versions.